---
- name: Deploy VM on Vmware
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    instance_name: "dummy"

  collections:
  - name: community.vmware
    source: https://galaxy.ansible.com

  roles:
    - role: vmw
      #instance_role: "undefined"
      create_vmware_guest_task: True
